### ISSUE TITLE
react_1.styled is not a function

### ISSUE THREAD

**Issue by rwieruch** [stitchesjs/stitches#973]
I took the evening to migrate my library from using styled-components to stitches. When I start Storybook, the styles get applied perfectly. However, when I build the library and install it somewhere else, I get: `react_1.styled is not a function`. (see [here](https://stackblitz.com/edit/react-ts-mgmsc3?file=Hello.tsx)).

This is the branch of my library where I am using stitches now: https://github.com/table-library/react-table-library/tree/feat/stitches Compared to using styled-components (or emotion), I thought I wouldn't have to change anything in the tsconfig.json or babel.config.js to make it work. Or am I wrong here? I am using rollup to bundle everything.

Thanks for your help! Really looking forward getting this to work!

**Comment by rwieruch** [comment]
Side-note: Wondering if it has something to do with @babel/runtime being needed, because radix-ui uses it as dependency too: https://github.com/radix-ui/primitives/blob/main/packages/react/checkbox/package.json

**Comment by arturbien** [comment]
Having the same issue. I am not using radix tho. The only dependencies I am using so far are react and stitches.

@rwieruch did you manage to get around this issue?

**Comment by rwieruch** [comment]
I am not using radix either. No, didn't find a solution yet. Worst case I have to use emotion instead, but I really hope to use stitches here :)

**Comment by hadihallak** [comment]
Hey @rwieruch 
Would you be able to provide us with a minimalistic reproduction of the issue (the smaller the repro, the faster we can debug it)?

**Comment by arturbien** [comment]
@hadihallak we went with styled-components instead

**Comment by hadihallak** [comment]
@arturbien Thanks for your quick response. 
Will be closing this for now but if anyone else is having the issue,  feel free to re-open this and post a minimal-repro

**Comment by jnoer** [comment]
I get the same

**Comment by TheeMattOliver** [comment]
Please re-open.

Brand new minimal lib, using Stitches. 

On the consumer side:

`0 , _react.styled) is not a function`

**Comment by TheeMattOliver** [comment]
Repro:

https://github.com/TheeMattOliver/radix-stitches-styled-not-function-repro

**Comment by drigofonte** [comment]
Hi there, getting a similar issue in our build pipeline where we get the following error message when running our tests:

`TypeError: (0 , core_1.keyframes) is not a function

       5 | const colors = {};
       6 |
    >  7 | const spin = keyframes({
         |                       ^
       8 |   "0%": { transform: "rotate(0deg)" },
       9 |   "100%": { transform: "rotate(360deg)" },
      10 | });

      at Object.<anonymous> (base-ui/components/button/button.styles.ts:7:23)
      at Object.<anonymous> (base-ui/components/button/button.tsx:4:1)
      at Object.<anonymous> (base-ui/components/button/index.ts:1:1)
      at Object.<anonymous> (base-ui/components/badge/badge.spec.tsx:4:1)`

Has anyone come up with a solution or explanation of what might be causing it?

Thanks.

**Comment by chrislicodes** [comment]
Any updates on this one?
Similar error on consumer side for a fresh CRA:

`Uncaught TypeError: (0 , _react.createStitches) is not a function`

**Comment by jnoer** [comment]
React 18 is not supported. See https://github.com/stitchesjs/stitches/issues/1059

We have switched over to Emotion.

**Comment by renecruces** [comment]
I've been experiencing the same problem. In my case, I've noticed that webpack was not including this package, and was importing the path to the .cjs module instead.

![image](https://user-images.githubusercontent.com/52537668/221768815-ea668809-f679-48e9-9094-0130acba5550.png)

![image](https://user-images.githubusercontent.com/52537668/221768745-088aa5cf-662c-4bf6-8a4e-c60535555625.png)
 


So I modified my babel config with the following in order to resolve the package accordingly:
```
module.exports = {
  ...
  plugins: [
    [
      'module-resolver', // https://www.npmjs.com/package/babel-plugin-module-resolver
      {
        root: ['./src'],
        alias: {
          '@stitches/react': path.resolve(__dirname, './node_modules/@stitches/react')
        }
      }
    ],
    ...
  ]
};

```
